# Generated by Django 5.0.7 on 2024-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='label',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
